### ISSUE TITLE
shut the fuck up

### ISSUE THREAD

**Issue by iProgramMC** [growaloneman/razvaneek#2]
you are on r/quityourbullshit watch your fucking mouth https://www.reddit.com/r/quityourbullshit/comments/eigll6/someone_is_claiming_copyright_for_my_game/

you are just retarded at this point

**Comment by growaloneman** [comment]
Lol nice try. You are mad that you got exposed for claiming ownership of my game.

**Comment by iProgramMC** [comment]
Do you even have source retard?

**Comment by iProgramMC** [comment]
@growaloneman

**Comment by growaloneman** [comment]
Yes, I do have the source. Stop crying about it @iProgramMC
